/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package io.github.shinusuresh.gradle.spring.banner

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class GradleSpringBannerPlugin implements Plugin<Project> {
    void apply(Project project) {
        // Register a task
        project.tasks.register("greeting") {
            doLast {
                println("Hello from plugin 'io.github.shinusuresh.gradle.spring.banner.greeting'")
            }
        }
    }
}
