/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package io.github.ss.gradle.spring.banner


import org.gradle.testkit.runner.GradleRunner
import spock.lang.Shared
import spock.lang.Specification

/**
 * A simple functional test for the 'io.github.ss.gradle.spring.banner' plugin.
 */
class GradleSpringBannerPluginFunctionalTest extends Specification {

    @Shared
    def projectName = 'Banner'

    @Shared
    def projectDir = new File("build/functionalTest")

    def setupSpec() {
        projectDir.deleteDir()
        projectDir.mkdirs()
        new File(projectDir, "settings.gradle") << """
            rootProject.name = "$projectName" 
        """
        new File(projectDir, "build.gradle") << """
            plugins {
                id('io.github.ss.gradle.spring.banner')
            }
        """
    }

    def "banner file is created"() {
        given:
        projectDir.exists()

        when:
        def runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("tasks")
        runner.withProjectDir(projectDir)
        def result = runner.build()

        then:
        def bannerOutPutFile = new File(projectDir, 'src/main/resources/banner.txt')
        bannerOutPutFile.exists()
    }
}
