/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package io.github.ss.gradle.spring.banner

import com.github.dtmo.jfiglet.FigFontResources
import com.github.dtmo.jfiglet.FigletRenderer
import org.gradle.api.Plugin
import org.gradle.api.Project

/**
 * A simple 'hello world' plugin.
 */
class GradleSpringBannerPlugin implements Plugin<Project> {

    void apply(Project project) {
        def bannerOutPutDirectory = project.file('src/main/resources')
        def bannerOutputFileName = 'banner.txt'

        def exist = bannerOutPutDirectory.exists()
        println "Exist -> $exist"
        if (!bannerOutPutDirectory.exists()) {
            bannerOutPutDirectory.mkdirs()
        }

        def figletRenderer = new FigletRenderer(FigFontResources.loadFigFontResource(FigFontResources.STANDARD_FLF))

        def treeBuilder = new FileTreeBuilder(bannerOutPutDirectory)
        treeBuilder.file(bannerOutputFileName) {
            withWriter {
                it.write(figletRenderer.renderText(project.name))
                it.writeLine('''
                    Version: ${application.version:1.0.0}
                    Server: ${server.address:localhost}:${server.port:8080} 
                    Active Profiles: ${spring.profiles.active:none}
                ''')
            }
        }
    }
}
